swagger: "2.0"

info:
  version: 1.0.0
  title: YCR API
  description: YCR API

schemes:
  - https
host: 
basePath: /api

paths:
  /companies:
    get:
      summary: Gets some companies
      description: Returns a list containing all companies. The list supports paging.
      responses:
        200:
          description: A list of Company
          schema:
            $ref: "#/definitions/Companies"
        500:
          $ref: "#/responses/Standard500ErrorResponse"
    post:
      summary: Creates a company
      description: Adds a new person to the persons list.
      parameters:
        - name: name
          in: body
          description: The company to create.
          schema:
            $ref: "#/definitions/Company"
      responses:
        204:
          description: Company succesfully created.
        400:
          description: Company couldn't have been created.
        500:
          $ref: "#/responses/Standard500ErrorResponse"
          
  /companies/{id}:
    get:
      summary: Gets a company
      description: Returns a single company for its id.
      parameters:
        - name: id
          in: path
          required: true
          description: The company's id
          type: number
      responses:
        200:
          description: A Company
          schema:
            $ref: "#/definitions/Company"
        404:
          description: The Company does not exists.
        500:
          $ref: "#/responses/Standard500ErrorResponse"

definitions:
  Company:
    required:
      - name
    properties:
      name:
        type: string
  Companies:
    type: array
    items:
      $ref: "#/definitions/Company"
  Error:
    properties:
      code:
        type: string
      message:
        type: string

responses:
  Standard500ErrorResponse:
    description: An unexpected error occured.
    schema:
      $ref: "#/definitions/Error"